// THIS IS WHERE MY MAIN LOGIC WILL LIE

// INDEX FILES ARE CONSIDERED THE ENTRY POINT TO MY APPLICATION

// IF THIS IS YOUR ENTRY POINT, I MUST DO INQUIRER HERE

// THIS IS WHERE I DO MY FS WRITEFILE STUFF